name: dapr-workshop-loan-predictor
dependencies:
- fbprophet==0.5
- numpy>=1.16.0,<=1.16.2
- pandas>=0.21.0,<=0.23.4
- pip
- psutil>=5.2.2,<6.0.0
- python=3.7
- py-xgboost<=0.80
- scikit-learn>=0.19.0,<=0.20.3
- pip:
  - azureml-defaults==1.1.5.1
  - azureml-explain-model==1.1.5
  - azureml-train-automl-runtime==1.1.5.3
  - fastapi
  - inference-schema
  - pydantic
  - typing
  - uvicorn
channels:
- anaconda
- conda-forge