kind: Service
apiVersion: v1
metadata:
  name: bindings-ai-service
  labels:
    app: bindingsaiservice
spec:
  selector:
    app: bindingsaiservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "ai-service"
        dapr.io/port: "3000"
    spec:
      containers:
      - name: ai-service
        image: daprcr.azurecr.io/dapr/ai-service:latest
        ports:
          - containerPort: 3000