kind: Service
apiVersion: v1
metadata:
  name: bindings-loan-predictor
  labels:
    app: bindingsloanpredictor
spec:
  selector:
    app: bindingsloanpredictor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-predictor
  labels:
    app: loan-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-predictor
  template:
    metadata:
      labels:
        app: loan-predictor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "loan-predictor"
        dapr.io/port: "3000"
    spec:
      containers:
      - name: loan-predictor
        image: daprcr.azurecr.io/dapr/loan-predictor:latest
        ports:
          - containerPort: 3000