apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  metadata:
  - name: vaultName
    value: daprworkshopakv
  - name: spnClientId
    value: 0e0fbba3-708e-41b5-8860-78a14016cad9